package main

import (
	"bytes"
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerateSourceContainsExpectedRegistryScaffolding(t *testing.T) {
	source, err := generateSource("internal/standard/uids.tsv", []parsedEntry{
		{
			UID:      "1.2.840.10008.1.1",
			Name:     "Verification SOP Class",
			Keyword:  "Verification",
			TypeExpr: "SOPClass",
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	text := string(source)
	for _, want := range []string{
		"Code generated by cmd/dicomuidgen; DO NOT EDIT.",
		"Source file: internal/standard/uids.tsv",
		"package uid",
		"var Dictionary Registry = table{",
		"func EntriesByType(typ Type) []Entry {",
		"{UID: \"1.2.840.10008.1.1\", Name: \"Verification SOP Class\", Keyword: \"Verification\", Type: SOPClass}",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated source is missing %q\n%s", want, text)
		}
	}
}

func TestGenerateSourceSortsEntriesByUID(t *testing.T) {
	source, err := generateSource("internal/standard/uids.tsv", []parsedEntry{
		{UID: "1.2.840.10008.1.2.1", Name: "Explicit VR Little Endian", Keyword: "ExplicitVRLittleEndian", TypeExpr: "TransferSyntax"},
		{UID: "1.2.840.10008.1.1", Name: "Verification SOP Class", Keyword: "Verification", TypeExpr: "SOPClass"},
	})
	if err != nil {
		t.Fatal(err)
	}

	text := string(source)
	first := strings.Index(text, "Verification")
	second := strings.Index(text, "ExplicitVRLittleEndian")
	if first == -1 || second == -1 {
		t.Fatalf("could not locate expected entries in generated source\n%s", text)
	}
	if first > second {
		t.Fatalf("entries are not sorted by UID:\n%s", text)
	}
}

func TestGenerateSourceCompiles(t *testing.T) {
	source, err := generateSource("internal/standard/uids.tsv", []parsedEntry{
		{UID: "1.2.840.10008.1.1", Name: "Verification SOP Class", Keyword: "Verification", TypeExpr: "SOPClass"},
		{UID: "1.2.840.10008.1.2.2", Name: "Explicit VR Big Endian (Retired)", Keyword: "ExplicitVRBigEndian", TypeExpr: "TransferSyntax", Retired: true},
	})
	if err != nil {
		t.Fatal(err)
	}

	tempDir := t.TempDir()
	uidSource, err := os.ReadFile(filepath.Join("..", "..", "dictionary", "uid", "uid.go"))
	if err != nil {
		t.Fatal(err)
	}

	goMod := "module generatedcheck\n\ngo 1.22\n"
	if err := os.WriteFile(filepath.Join(tempDir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tempDir, "uid.go"), uidSource, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tempDir, "std_gen.go"), source, 0o644); err != nil {
		t.Fatal(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "go", "test", ".")
	cmd.Dir = tempDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) || ctx.Err() == context.DeadlineExceeded {
			t.Fatalf("generated source compile check timed out after %s\n%s", 30*time.Second, output)
		}
		t.Fatalf("generated source did not compile: %v\n%s", err, output)
	}
	if !bytes.Contains(output, []byte("[no test files]")) {
		t.Fatalf("unexpected go test output:\n%s", output)
	}
}
