package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

type templateData struct {
	Entries    []parsedEntry
	SourcePath string
}

var outputTemplate = template.Must(template.New("std").Parse(`// Code generated by cmd/dicomuidgen; DO NOT EDIT.
//
// Source file: {{.SourcePath}}
// Source origin: DICOM PS3.6 table A-1, vendored in internal/standard/uids.tsv
// Implementation notes:
// - lookup is case-insensitive by keyword in Go to match the existing dictionary contract
// - the registry is package-local generated Go code instead of per-type constants

package uid

import "strings"

var Dictionary Registry = table{
	byUID:     map[string]Entry{},
	byKeyword: map[string]Entry{},
	byType:    map[Type][]Entry{},
}

type table struct {
	byUID     map[string]Entry
	byKeyword map[string]Entry
	byType    map[Type][]Entry
}

func (t table) ByUID(uid string) (Entry, bool) {
	e, ok := t.byUID[NormalizeUID(uid)]
	return e, ok
}

func (t table) ByKeyword(keyword string) (Entry, bool) {
	e, ok := t.byKeyword[strings.ToLower(keyword)]
	return e, ok
}

// EntriesByType returns a stable snapshot of the registered entries for one UID type.
func EntriesByType(typ Type) []Entry {
	t := Dictionary.(table)
	entries := t.byType[typ]
	out := make([]Entry, len(entries))
	copy(out, entries)
	return out
}

func init() {
	t := Dictionary.(table)
	for _, e := range entries {
		t.byUID[e.UID] = e
		key := strings.ToLower(e.Keyword)
		if _, ok := t.byKeyword[key]; !ok {
			t.byKeyword[key] = e
		}
		t.byType[e.Type] = append(t.byType[e.Type], e)
	}
}

var entries = []Entry{
{{- range .Entries }}
	{UID: {{printf "%q" .UID}}, Name: {{printf "%q" .Name}}, Keyword: {{printf "%q" .Keyword}}, Type: {{.TypeExpr}}{{if .Retired}}, Retired: true{{end}}},
{{- end }}
}
`))

func generateSource(inputPath string, entries []parsedEntry) ([]byte, error) {
	sortedEntries := slices.Clone(entries)
	slices.SortFunc(sortedEntries, func(a, b parsedEntry) int {
		if a.UID < b.UID {
			return -1
		}
		if a.UID > b.UID {
			return 1
		}
		if a.Keyword < b.Keyword {
			return -1
		}
		if a.Keyword > b.Keyword {
			return 1
		}
		return 0
	})

	var buf bytes.Buffer
	if err := outputTemplate.Execute(&buf, templateData{
		Entries:    sortedEntries,
		SourcePath: displaySourcePath(inputPath),
	}); err != nil {
		return nil, fmt.Errorf("render generated source: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func writeGeneratedFile(path string, source []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, source, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func displaySourcePath(path string) string {
	clean := filepath.ToSlash(filepath.Clean(path))
	const canonical = "internal/standard/uids.tsv"
	if strings.HasSuffix(clean, canonical) {
		return canonical
	}
	return clean
}
