// Code generated by cmd/deidtablegen from DICOM PS3.16 2026b Annex O and Section 8.3; DO NOT EDIT.

package deid

const (
	GeneratedRetiredCodeStandardVersion            = "PS3.16 2026b"
	GeneratedRetiredCodeSourceURL                  = "https://dicom.nema.org/medical/dicom/2026b/output/chtml/part16/chapter_O.html"
	GeneratedRetiredCodePolicySourceURL            = "https://dicom.nema.org/medical/dicom/2026b/output/chtml/part16/sect_8.3.html"
	GeneratedRetiredCodeStructuredContentSourceURL = "https://dicom.nema.org/medical/dicom/2026b/output/chtml/part15/sect_E.3.4.html"
	GeneratedRetiredCodeProjectionSHA256           = "6f7688d225e3e558e5279d3fba5e26176d207e332465ab0a9769cdf65bc5e6c1"
	GeneratedRetiredCodeRowCount                   = 30
)

type generatedRetiredCodeAlias struct {
	OldCodeValue                  string
	OldCodingSchemeDesignator     string
	CurrentCodeValue              string
	CurrentCodingSchemeDesignator string
}

var generatedRetiredCodeAliases = []generatedRetiredCodeAlias{
	{OldCodeValue: "DD-60002", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "116224001", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DD-60002", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "116224001", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DD-60002", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "116224001", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DF-0068E", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "398325003", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DF-0068E", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "398325003", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DF-0068E", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "398325003", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DF-0070B", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "398164008", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DF-0070B", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "398164008", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "DF-0070B", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "398164008", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "F-00033", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "271921002", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "F-00033", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "271921002", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "F-00033", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "271921002", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "F-02455", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "160476009", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "F-02455", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "160476009", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "F-02455", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "160476009", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-C0E3", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "363698007", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-C0E3", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "363698007", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-C0E3", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "363698007", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-D320", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "397898000", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-D320", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "397898000", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-D320", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "397898000", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-D321", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "398201009", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-D321", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "398201009", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "G-D321", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "398201009", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "PA-30029", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "440252007", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "PA-30029", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "440252007", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "PA-30029", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "440252007", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "R-42B89", OldCodingSchemeDesignator: "99SDM", CurrentCodeValue: "371524004", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "R-42B89", OldCodingSchemeDesignator: "SNM3", CurrentCodeValue: "371524004", CurrentCodingSchemeDesignator: "SCT"},
	{OldCodeValue: "R-42B89", OldCodingSchemeDesignator: "SRT", CurrentCodeValue: "371524004", CurrentCodingSchemeDesignator: "SCT"},
}
