package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"strings"
)

const (
	structuredContentSourceURL         = "https://dicom.nema.org/medical/dicom/2026b/output/chtml/part15/sect_E.3.4.html"
	expectedStructuredContentSHA256    = "81d2e89aa42dc2d3331aad70cc03b71b21e9a79c54edfe759cf68e6504430c69"
	expectedStructuredContentRowCount  = 211
	structuredContentSourceColumnCount = 14
	structuredContentActionColumnCount = 8
)

type structuredContentRow struct {
	CodeValue              string
	CodingSchemeDesignator string
	ValueType              string
	Actions                [structuredContentActionColumnCount]string
}

func parseStructuredContentTable(r io.Reader) ([]structuredContentRow, error) {
	decoder := xml.NewDecoder(r)
	anchorSeen := false
	inTable := false
	tableDepth := 0
	inBody := false
	bodyDepth := 0
	inRow := false
	inCell := false
	var cellText strings.Builder
	var cells []string
	var rows []structuredContentRow

	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("decode XHTML: %w", err)
		}

		switch token := token.(type) {
		case xml.StartElement:
			if !anchorSeen && token.Name.Local == "a" && attribute(token.Attr, "id") == "table_E.3.4-1" {
				anchorSeen = true
				continue
			}
			if anchorSeen && !inTable && token.Name.Local == "table" {
				inTable = true
				tableDepth = 1
				continue
			}
			if !inTable {
				continue
			}
			if token.Name.Local == "table" {
				tableDepth++
			}
			if token.Name.Local == "tbody" && tableDepth == 1 {
				inBody = true
				bodyDepth = 1
				continue
			}
			if inBody && token.Name.Local == "tbody" {
				bodyDepth++
			}
			if inBody && bodyDepth == 1 && token.Name.Local == "tr" {
				inRow = true
				cells = cells[:0]
				continue
			}
			if inRow && token.Name.Local == "td" {
				if inCell {
					return nil, fmt.Errorf("nested table cell in row %d", len(rows)+1)
				}
				inCell = true
				cellText.Reset()
			}
		case xml.CharData:
			if inCell {
				cellText.Write(token)
			}
		case xml.EndElement:
			if !inTable {
				continue
			}
			if inRow && inCell && token.Name.Local == "td" {
				cells = append(cells, normalizeText(cellText.String()))
				inCell = false
				continue
			}
			if inBody && bodyDepth == 1 && inRow && token.Name.Local == "tr" {
				row, projectErr := projectStructuredContentRow(cells, len(rows)+1)
				if projectErr != nil {
					return nil, projectErr
				}
				rows = append(rows, row)
				inRow = false
				continue
			}
			if inBody && token.Name.Local == "tbody" {
				bodyDepth--
				if bodyDepth == 0 {
					inBody = false
				}
				continue
			}
			if token.Name.Local == "table" {
				tableDepth--
				if tableDepth == 0 {
					inTable = false
				}
			}
		}
	}

	if !anchorSeen {
		return nil, fmt.Errorf("anchor table_E.3.4-1 not found")
	}
	if len(rows) == 0 {
		return nil, fmt.Errorf("Table E.3.4-1 body has no rows")
	}
	return rows, nil
}

func projectStructuredContentRow(cells []string, rowNumber int) (structuredContentRow, error) {
	if len(cells) != structuredContentSourceColumnCount {
		return structuredContentRow{}, fmt.Errorf("row %d has %d columns, want %d", rowNumber, len(cells), structuredContentSourceColumnCount)
	}
	row := structuredContentRow{
		CodeValue:              cells[1],
		CodingSchemeDesignator: cells[2],
		ValueType:              cells[3],
	}
	if row.CodeValue == "" || row.CodingSchemeDesignator == "" || row.ValueType == "" {
		return structuredContentRow{}, fmt.Errorf("row %d has an empty code value, coding scheme designator, or value type", rowNumber)
	}
	copy(row.Actions[:], cells[6:])
	return row, nil
}

func canonicalStructuredContentProjection(rows []structuredContentRow) []byte {
	var projection bytes.Buffer
	for _, row := range rows {
		projection.WriteString(row.CodeValue)
		projection.WriteByte('\t')
		projection.WriteString(row.CodingSchemeDesignator)
		projection.WriteByte('\t')
		projection.WriteString(row.ValueType)
		for _, action := range row.Actions {
			projection.WriteByte('\t')
			projection.WriteString(action)
		}
		projection.WriteByte('\n')
	}
	return projection.Bytes()
}

func structuredContentProjectionSHA256(rows []structuredContentRow) string {
	digest := sha256.Sum256(canonicalStructuredContentProjection(rows))
	return hex.EncodeToString(digest[:])
}

func renderStructuredContent(rows []structuredContentRow) ([]byte, error) {
	checksum := structuredContentProjectionSHA256(rows)
	var source bytes.Buffer
	source.WriteString("// Code generated by cmd/deidtablegen from DICOM PS3.15 2026b Table E.3.4-1; DO NOT EDIT.\n")
	source.WriteString("\npackage deid\n\n")
	source.WriteString("const (\n")
	fmt.Fprintf(&source, "\tGeneratedStructuredContentStandardVersion = %s\n", strconv.Quote(standardVersion))
	fmt.Fprintf(&source, "\tGeneratedStructuredContentSourceURL = %s\n", strconv.Quote(structuredContentSourceURL))
	fmt.Fprintf(&source, "\tGeneratedStructuredContentProjectionSHA256 = %s\n", strconv.Quote(checksum))
	fmt.Fprintf(&source, "\tGeneratedStructuredContentRowCount = %d\n", len(rows))
	source.WriteString(")\n\n")
	source.WriteString("type generatedStructuredContentRule struct {\n")
	source.WriteString("\tCodeValue string\n")
	source.WriteString("\tCodingSchemeDesignator string\n")
	source.WriteString("\tValueType string\n")
	source.WriteString("\t// Actions are Basic, UIDs, Device, Institution, Patient Characteristics, Full Dates, Modified Dates, and Clean Descriptors.\n")
	source.WriteString("\tActions [8]ActionCode\n")
	source.WriteString("}\n\n")
	source.WriteString("var generatedStructuredContentRules = []generatedStructuredContentRule{\n")
	for _, row := range rows {
		fmt.Fprintf(&source, "\t{CodeValue: %s, CodingSchemeDesignator: %s, ValueType: %s, Actions: [8]ActionCode{", strconv.Quote(row.CodeValue), strconv.Quote(row.CodingSchemeDesignator), strconv.Quote(row.ValueType))
		for index, action := range row.Actions {
			if index != 0 {
				source.WriteString(", ")
			}
			source.WriteString(strconv.Quote(action))
		}
		source.WriteString("}},\n")
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return formatted, nil
}
