package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"text/template"
	"time"
)

const sourceURL = "https://raw.githubusercontent.com/DCMTK/dcmtk/master/dcmdata/data/dicom.dic"

type templateData struct {
	Entries     []parsedEntry
	GeneratedAt string
	SourcePath  string
	SourceURL   string
}

var outputTemplate = template.Must(template.New("std").Parse(`// Code generated by cmd/dicomdictgen; DO NOT EDIT.
//
// Source file: {{.SourcePath}}
// Source URL: {{.SourceURL}}
// Generated at: {{.GeneratedAt}}
// Implementation notes:
// - repeating tag ranges are expanded to concrete tags because dicom-go currently exposes exact-tag lookup only
// - context-dependent VRs preserve their complete allowed VR set while Entry.VR keeps its compatible fallback
// - Entry.Name is derived from the DICOM keyword because dicom.dic does not provide the long display name

package std

import (
	"strings"

	"github.com/ThalesMMS/dicom-go/core"
	"github.com/ThalesMMS/dicom-go/dictionary"
)

var Dictionary dictionary.DataDictionary = table{
	byTag:   map[core.Tag]dictionary.Entry{},
	byKey:   map[string]dictionary.Entry{},
	vrSpecs: map[core.Tag]dictionary.VRSpec{},
}

type table struct {
	byTag   map[core.Tag]dictionary.Entry
	byKey   map[string]dictionary.Entry
	vrSpecs map[core.Tag]dictionary.VRSpec
}

func (t table) ByTag(tag core.Tag) (dictionary.Entry, bool) {
	e, ok := t.byTag[tag]
	return e, ok
}

func (t table) ByKeyword(keyword string) (dictionary.Entry, bool) {
	e, ok := t.byKey[strings.ToLower(keyword)]
	return e, ok
}

func (t table) VRSpecByTag(tag core.Tag) (dictionary.VRSpec, bool) {
	if spec, ok := t.vrSpecs[tag]; ok {
		return spec, true
	}
	e, ok := t.byTag[tag]
	if !ok || e.VR == "" {
		return dictionary.VRSpec{}, false
	}
	return dictionary.NewVRSpec(e.VR), true
}

func init() {
	t := Dictionary.(table)
	for _, e := range entries {
		t.byTag[e.Tag] = e
		key := strings.ToLower(e.Keyword)
		if _, ok := t.byKey[key]; !ok {
			t.byKey[key] = e
		}
	}
	for tag, spec := range contextualVRSpecs {
		t.vrSpecs[tag] = spec
	}
}

var contextualVRSpecs = map[core.Tag]dictionary.VRSpec{
{{- range .Entries }}{{if .ContextualVRExpr}}
	core.NewTag({{printf "0x%04X" .Tag.Group}}, {{printf "0x%04X" .Tag.Element}}): dictionary.NewContextualVRSpec({{.ContextualVRExpr}}),{{end}}{{end}}
}

var entries = []dictionary.Entry{
{{- range .Entries }}
	{Tag: core.NewTag({{printf "0x%04X" .Tag.Group}}, {{printf "0x%04X" .Tag.Element}}), VR: {{.VRExpr}}, Keyword: {{printf "%q" .Keyword}}, Name: {{printf "%q" .Name}}, VM: {{printf "%q" .VM}}{{if .Retired}}, Retired: true{{end}}},
{{- end }}
}
`))

func generateSource(inputPath string, entries []parsedEntry, generatedAt time.Time) ([]byte, error) {
	sortedEntries := slices.Clone(entries)
	slices.SortFunc(sortedEntries, func(a, b parsedEntry) int {
		if cmp := a.Tag.Compare(b.Tag); cmp != 0 {
			return cmp
		}
		if a.Keyword < b.Keyword {
			return -1
		}
		if a.Keyword > b.Keyword {
			return 1
		}
		return 0
	})

	var buf bytes.Buffer
	if err := outputTemplate.Execute(&buf, templateData{
		Entries:     sortedEntries,
		GeneratedAt: formatGenerationTimestamp(generatedAt),
		SourcePath:  displaySourcePath(inputPath),
		SourceURL:   sourceURL,
	}); err != nil {
		return nil, fmt.Errorf("render generated source: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func formatGenerationTimestamp(ts time.Time) string {
	if ts.IsZero() {
		return "unknown"
	}
	return ts.UTC().Format(time.RFC3339)
}

var fileCreatedOnPattern = regexp.MustCompile(`^#\s*File created on ([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})\b`)

func dictionaryTimestamp(path string) (ts time.Time, err error) {
	file, err := os.Open(path)
	if err != nil {
		return time.Time{}, fmt.Errorf("open %s for header scan: %w", path, err)
	}
	defer func() {
		if cerr := file.Close(); cerr != nil {
			cerr = fmt.Errorf("close %s after header scan: %w", path, cerr)
			if err == nil {
				err = cerr
				return
			}
			err = errors.Join(err, cerr)
		}
	}()

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	for scanner.Scan() {
		line := scanner.Text()
		matches := fileCreatedOnPattern.FindStringSubmatch(line)
		if len(matches) != 2 {
			continue
		}

		parsedTs, parseErr := time.Parse("2006-01-02 15:04:05", matches[1])
		if parseErr != nil {
			err = fmt.Errorf("parse source timestamp in %s: %w", path, parseErr)
			return time.Time{}, err
		}
		ts = parsedTs.UTC()
		return ts.UTC(), nil
	}
	if scanErr := scanner.Err(); scanErr != nil {
		err = fmt.Errorf("scan %s for source timestamp: %w", path, scanErr)
		return time.Time{}, err
	}
	return time.Time{}, nil
}

func writeGeneratedFile(path string, source []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, source, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func displaySourcePath(path string) string {
	clean := filepath.ToSlash(filepath.Clean(path))
	const canonical = "internal/standard/dicom.dic"
	if strings.HasSuffix(clean, canonical) {
		return canonical
	}
	return clean
}
