package main

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ThalesMMS/dicom-go/core"
)

func TestGenerateSourceContainsExpectedRegistryScaffolding(t *testing.T) {
	source, err := generateSource("internal/standard/dicom.dic", []parsedEntry{
		{
			Tag:     core.NewTag(0x0010, 0x0010),
			VRExpr:  "core.VRPN",
			Keyword: "PatientName",
			Name:    "Patient Name",
			VM:      "1",
		},
		{
			Tag:              core.NewTag(0x0028, 0x0106),
			VRExpr:           "core.VRUS",
			ContextualVRExpr: "dictionary.ContextualVRXS",
			Keyword:          "SmallestImagePixelValue",
			Name:             "Smallest Image Pixel Value",
			VM:               "1",
		},
	}, time.Date(2026, 4, 22, 12, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}

	text := string(source)
	for _, want := range []string{
		"Code generated by cmd/dicomdictgen; DO NOT EDIT.",
		"Source file: internal/standard/dicom.dic",
		"Source URL: https://raw.githubusercontent.com/DCMTK/dcmtk/master/dcmdata/data/dicom.dic",
		"Generated at: 2026-04-22T12:00:00Z",
		"package std",
		"var Dictionary dictionary.DataDictionary = table{",
		"func init() {",
		"func (t table) VRSpecByTag(tag core.Tag) (dictionary.VRSpec, bool)",
		"dictionary.NewContextualVRSpec(dictionary.ContextualVRXS)",
		"{Tag: core.NewTag(0x0010, 0x0010), VR: core.VRPN, Keyword: \"PatientName\", Name: \"Patient Name\", VM: \"1\"}",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated source is missing %q\n%s", want, text)
		}
	}
}

func TestGenerateSourceSortsEntriesByTag(t *testing.T) {
	source, err := generateSource("internal/standard/dicom.dic", []parsedEntry{
		{Tag: core.NewTag(0x0010, 0x0020), VRExpr: "core.VRLO", Keyword: "PatientID", Name: "Patient ID", VM: "1"},
		{Tag: core.NewTag(0x0008, 0x0018), VRExpr: "core.VRUI", Keyword: "SOPInstanceUID", Name: "SOP Instance UID", VM: "1"},
	}, time.Date(2026, 4, 22, 12, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}

	text := string(source)
	first := strings.Index(text, "SOPInstanceUID")
	second := strings.Index(text, "PatientID")
	if first == -1 || second == -1 {
		t.Fatalf("could not locate expected entries in generated source\n%s", text)
	}
	if first > second {
		t.Fatalf("entries are not sorted by tag:\n%s", text)
	}
}

func TestGenerateSourceCompiles(t *testing.T) {
	source, err := generateSource("internal/standard/dicom.dic", []parsedEntry{
		{Tag: core.NewTag(0x0010, 0x0010), VRExpr: "core.VRPN", Keyword: "PatientName", Name: "Patient Name", VM: "1"},
		{Tag: core.NewTag(0x0028, 0x3006), VRExpr: "core.VROW", Keyword: "LUTData", Name: "LUT Data", VM: "1-n"},
		{Tag: core.NewTag(0x0004, 0x1504), VRExpr: "core.VRUL", Keyword: "MRDRDirectoryRecordOffset", Name: "MRDR Directory Record Offset", VM: "1", Retired: true},
	}, time.Date(2026, 4, 22, 12, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}

	tempDir := t.TempDir()
	repoRoot := filepath.Clean(filepath.Join(mustAbs(t, "."), "..", ".."))
	repoRoot = filepath.ToSlash(repoRoot)

	goMod := "module generatedcheck\n\ngo 1.22\n\nrequire github.com/ThalesMMS/dicom-go v0.0.0\n\nreplace github.com/ThalesMMS/dicom-go => " + repoRoot + "\n"
	if err := os.WriteFile(filepath.Join(tempDir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tempDir, "std_gen.go"), source, 0o644); err != nil {
		t.Fatal(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "go", "test", ".")
	cmd.Dir = tempDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) || ctx.Err() == context.DeadlineExceeded {
			t.Fatalf("generated source compile check timed out after %s\n%s", 30*time.Second, output)
		}
		t.Fatalf("generated source did not compile: %v\n%s", err, output)
	}
}

func mustAbs(t *testing.T, path string) string {
	t.Helper()

	abs, err := filepath.Abs(path)
	if err != nil {
		t.Fatal(err)
	}
	return abs
}
