// Package validation provides opt-in validation and lifecycle hooks with
// PHI-redacted diagnostics by default
// for DICOM elements and data sets. It validates encoded structure and basic
// value representation rules; it does not claim complete IOD conformance.
package validation

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/ThalesMMS/dicom-go/core"
	"github.com/ThalesMMS/dicom-go/dictionary"
	"github.com/ThalesMMS/dicom-go/transfer"
)

const (
	NoItem             = -1
	DefaultMaxFindings = 256
	DefaultMaxDepth    = 64
	DefaultMaxElements = 1_000_000
)

var (
	ErrValidationFailed = errors.New("dicom validation failed")
	ErrInvalidPolicy    = errors.New("dicom validation policy is invalid")
	ErrHookFailed       = errors.New("dicom validation hook failed")
	ErrHookAction       = errors.New("dicom validation hook action is invalid for this lifecycle point")
	ErrValidationLimit  = errors.New("dicom validation resource limit exceeded")
)

type Mode uint8

const (
	// ModePreserve collects findings without changing their severity or
	// rejecting the caller-owned data set. It is the zero value.
	ModePreserve Mode = iota
	// ModeWarn downgrades validation errors to warnings and preserves data.
	ModeWarn
	// ModeStrict returns ErrValidationFailed when an error finding is emitted.
	ModeStrict
)

type Severity string

const (
	SeverityInfo    Severity = "info"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)

type Code string

const (
	CodeValueLength       Code = "vr.value_length"
	CodeValuePadding      Code = "vr.padding"
	CodeReservedBytes     Code = "vr.reserved_bytes"
	CodeValueRepertoire   Code = "vr.repertoire"
	CodeValueFormat       Code = "vr.format"
	CodeValueRange        Code = "vr.range"
	CodeValueKind         Code = "vr.value_kind"
	CodeValueMultiplicity Code = "dictionary.vm"
	CodeDictionaryVR      Code = "dictionary.vr"
	CodeDuplicateElement  Code = "dataset.duplicate"
	CodeElementOrder      Code = "dataset.order"
	CodeRequiredUID       Code = "dataset.required_uid"
	CodeSequenceStructure Code = "dataset.sequence_structure"
	CodeFragmentStructure Code = "dataset.fragment_structure"
	CodePixelMetadata     Code = "dataset.pixel_metadata"
	CodeDataSetRule       Code = "dataset.rule"
	CodeFileMetaMismatch  Code = "file_meta.mismatch"
	CodeHookDiagnostic    Code = "hook.diagnostic"
	CodeHookTransformed   Code = "hook.transformed"
	CodeHookFiltered      Code = "hook.filtered"
	CodeHookSkipped       Code = "hook.skipped"
	CodeHookDeferred      Code = "hook.deferred"
	CodeHookPanic         Code = "hook.panic"
	CodeHookTimeout       Code = "hook.timeout"
	CodeHookError         Code = "hook.error"
	CodeHookAction        Code = "hook.invalid_action"
	CodeResourceLimit     Code = "validation.resource_limit"
)

type PathStep struct {
	Tag       core.Tag `json:"tag"`
	ItemIndex int      `json:"-"`
}

func (s PathStep) MarshalJSON() ([]byte, error) {
	type encodedStep struct {
		Tag       core.Tag `json:"tag"`
		ItemIndex *int     `json:"item_index,omitempty"`
	}
	encoded := encodedStep{Tag: s.Tag}
	if s.ItemIndex >= 0 {
		index := s.ItemIndex
		encoded.ItemIndex = &index
	}
	return json.Marshal(encoded)
}

type Path []PathStep

func (p Path) Clone() Path {
	if len(p) == 0 {
		return nil
	}
	return append(Path(nil), p...)
}

func (p Path) String() string {
	parts := make([]string, len(p))
	for i, step := range p {
		parts[i] = step.Tag.String()
		if step.ItemIndex >= 0 {
			parts[i] += fmt.Sprintf("[%d]", step.ItemIndex)
		}
	}
	return strings.Join(parts, "/")
}

type Finding struct {
	Path       Path      `json:"path,omitempty"`
	Tag        core.Tag  `json:"tag"`
	VR         core.VR   `json:"vr,omitempty"`
	ExpectedVR []core.VR `json:"expected_vr,omitempty"`
	Rule       string    `json:"rule,omitempty"`
	Severity   Severity  `json:"severity"`
	Code       Code      `json:"code"`
	Offset     int64     `json:"offset,omitempty"`
	OffsetSet  bool      `json:"offset_set,omitempty"`
	Hook       string    `json:"hook,omitempty"`
	// Message is generated by the library and never contains an element value.
	Message string `json:"message"`

	occurrence int
}

type ChangeKind string

const (
	ChangeTransformed ChangeKind = "transformed"
	ChangeFiltered    ChangeKind = "filtered"
	ChangeSkipped     ChangeKind = "skipped"
	ChangeDeferred    ChangeKind = "deferred"
)

type Change struct {
	Path Path       `json:"path,omitempty"`
	Tag  core.Tag   `json:"tag"`
	Hook string     `json:"hook"`
	Kind ChangeKind `json:"kind"`
}

type Report struct {
	Findings  []Finding `json:"findings,omitempty"`
	Changes   []Change  `json:"changes,omitempty"`
	Truncated bool      `json:"truncated,omitempty"`
	Dropped   int       `json:"dropped,omitempty"`
}

func (r Report) Count(code Code) int {
	count := 0
	for _, finding := range r.Findings {
		if finding.Code == code {
			count++
		}
	}
	return count
}

func (r Report) HasErrors() bool {
	for _, finding := range r.Findings {
		if finding.Severity == SeverityError {
			return true
		}
	}
	return false
}

func (r Report) Clone() Report {
	clone := Report{Truncated: r.Truncated, Dropped: r.Dropped}
	clone.Findings = make([]Finding, len(r.Findings))
	for i, finding := range r.Findings {
		finding.Path = finding.Path.Clone()
		finding.ExpectedVR = append([]core.VR(nil), finding.ExpectedVR...)
		clone.Findings[i] = finding
	}
	clone.Changes = make([]Change, len(r.Changes))
	for i, change := range r.Changes {
		change.Path = change.Path.Clone()
		clone.Changes[i] = change
	}
	return clone
}

type Result struct {
	DataSet core.DataSet
	Report  Report
}

type ValidationError struct {
	Report Report
}

func (e *ValidationError) Error() string {
	count := len(e.Report.Findings)
	if count == 1 {
		return "dicom validation failed with 1 finding"
	}
	return fmt.Sprintf("dicom validation failed with %d findings", count)
}

func (e *ValidationError) Unwrap() error { return ErrValidationFailed }

type ElementContext struct {
	Element    core.Element
	DataSet    core.DataSet
	Path       Path
	Dictionary dictionary.DataDictionary
	ByteOrder  binary.ByteOrder
}

type VRResolver func(ElementContext, dictionary.Entry) []core.VR

// DataSetContext is a read-only view supplied to a registered dataset rule.
// Rules are trusted in-process code and must not mutate DataSet or include
// element values in returned diagnostics.
type DataSetContext struct {
	DataSet        core.DataSet
	Path           Path
	Dictionary     dictionary.DataDictionary
	ByteOrder      binary.ByteOrder
	TransferSyntax transfer.Syntax
}

type DataSetRule interface {
	ValidateDataSet(context.Context, DataSetContext) []Finding
}

type DataSetRuleFunc func(context.Context, DataSetContext) []Finding

func (f DataSetRuleFunc) ValidateDataSet(ctx context.Context, dataset DataSetContext) []Finding {
	if f == nil {
		return nil
	}
	return f(ctx, dataset)
}

type DataSetRuleRegistration struct {
	Name string
	Rule DataSetRule
}

type Options struct {
	Mode           Mode
	Dictionary     dictionary.DataDictionary
	MaxFindings    int
	StopFirst      bool
	MaxDepth       int
	MaxElements    int
	ByteOrder      binary.ByteOrder
	RequiredUIDs   []core.Tag
	ResolveVR      VRResolver
	Hooks          *HookChain
	TransferSyntax transfer.Syntax
	DataSetRules   []DataSetRuleRegistration
}

type reportBuilder struct {
	mode      Mode
	max       int
	stopFirst bool
	report    Report
}

func newReportBuilder(opts Options) (*reportBuilder, error) {
	if opts.Mode > ModeStrict || opts.MaxFindings < 0 || opts.MaxDepth < 0 || opts.MaxElements < 0 {
		return nil, ErrInvalidPolicy
	}
	max := opts.MaxFindings
	if max == 0 {
		max = DefaultMaxFindings
	}
	seenRules := make(map[string]struct{}, len(opts.DataSetRules))
	for _, registration := range opts.DataSetRules {
		if !hookNamePattern.MatchString(registration.Name) || registration.Rule == nil {
			return nil, ErrInvalidPolicy
		}
		if _, exists := seenRules[registration.Name]; exists {
			return nil, ErrInvalidPolicy
		}
		seenRules[registration.Name] = struct{}{}
	}
	return &reportBuilder{mode: opts.Mode, max: max, stopFirst: opts.StopFirst}, nil
}

// ValidateOptions checks validation resource bounds and mode values without
// executing any rules or hooks.
func ValidateOptions(opts Options) error {
	_, err := newReportBuilder(opts)
	return err
}

func (b *reportBuilder) add(finding Finding) {
	if b.stopFirst && len(b.report.Findings) > 0 {
		return
	}
	if finding.Severity == "" {
		finding.Severity = SeverityError
	}
	if b.mode == ModeWarn && finding.Severity == SeverityError {
		finding.Severity = SeverityWarning
	}
	if len(b.report.Findings)+len(b.report.Changes) >= b.max {
		b.report.Truncated = true
		b.report.Dropped++
		return
	}
	finding.Path = finding.Path.Clone()
	finding.ExpectedVR = append([]core.VR(nil), finding.ExpectedVR...)
	b.report.Findings = append(b.report.Findings, finding)
}

func (b *reportBuilder) change(change Change) {
	if len(b.report.Findings)+len(b.report.Changes) >= b.max {
		b.report.Truncated = true
		b.report.Dropped++
		return
	}
	change.Path = change.Path.Clone()
	b.report.Changes = append(b.report.Changes, change)
}

// ReportFromHookResult applies validation severity and collection policy to a
// hook result. Hook-provided values and error text are never copied into the
// generated report by this function.
func ReportFromHookResult(opts Options, result HookResult) (Report, error) {
	builder, err := newReportBuilder(opts)
	if err != nil {
		return Report{}, err
	}
	addHookResultToBuilder(builder, result)
	return builder.report.Clone(), nil
}

// MergeReports combines reports under one shared bound and applies the target
// mode's severity policy. Inputs are copied.
func MergeReports(opts Options, reports ...Report) (Report, error) {
	builder, err := newReportBuilder(opts)
	if err != nil {
		return Report{}, err
	}
	for _, report := range reports {
		for _, finding := range report.Findings {
			builder.add(finding)
		}
		for _, change := range report.Changes {
			builder.change(change)
		}
		builder.report.Dropped += report.Dropped
		builder.report.Truncated = builder.report.Truncated || report.Truncated
	}
	return builder.report.Clone(), nil
}

func (b *reportBuilder) shouldStop(opts Options) bool {
	return opts.StopFirst && len(b.report.Findings) > 0
}
