package uid_test

import (
	"os"
	"strings"
	"testing"

	uiddict "github.com/ThalesMMS/dicom-go/dictionary/uid"
)

func TestDictionaryByUIDCriticalEntries(t *testing.T) {
	tests := []uiddict.Entry{
		{UID: "1.2.840.10008.1.1", Name: "Verification SOP Class", Keyword: "Verification", Type: uiddict.SOPClass},
		{UID: "1.2.840.10008.1.2.1", Name: "Explicit VR Little Endian", Keyword: "ExplicitVRLittleEndian", Type: uiddict.TransferSyntax},
		{UID: "1.2.840.10008.5.1.4.1.1.2", Name: "CT Image Storage", Keyword: "CTImageStorage", Type: uiddict.SOPClass},
	}

	for _, want := range tests {
		got, ok := uiddict.Dictionary.ByUID(want.UID + " \x00")
		if !ok {
			t.Fatalf("ByUID(%q) did not find %q", want.UID, want.Keyword)
		}
		if got != want {
			t.Fatalf("ByUID(%q) = %#v, want %#v", want.UID, got, want)
		}
	}
}

func TestNormalizeUID(t *testing.T) {
	tests := map[string]string{
		"1.2.3 \x00":     "1.2.3",
		"1.2.3\x00 \x00": "1.2.3",
		" \x00":          "",
		" 1.2.3":         " 1.2.3",
		"1.2\x003 4":     "1.2\x003 4",
	}

	for input, want := range tests {
		if got := uiddict.NormalizeUID(input); got != want {
			t.Fatalf("NormalizeUID(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestParseTypeAndString(t *testing.T) {
	got, err := uiddict.ParseType(" Transfer Syntax ")
	if err != nil {
		t.Fatalf("ParseType() error = %v", err)
	}
	if got != uiddict.TransferSyntax {
		t.Fatalf("ParseType() = %v, want %v", got, uiddict.TransferSyntax)
	}
	if got.String() != "Transfer Syntax" {
		t.Fatalf("TransferSyntax.String() = %q, want Transfer Syntax", got.String())
	}

	_, err = uiddict.ParseType("Made Up Type")
	if err == nil || !strings.Contains(err.Error(), `unknown UID type "Made Up Type"`) {
		t.Fatalf("ParseType(unknown) error = %v, want unknown UID type message", err)
	}
	if got := uiddict.Type(255).String(); got != "Type(255)" {
		t.Fatalf("Type(255).String() = %q, want Type(255)", got)
	}
}

func TestDictionaryByKeywordIsCaseInsensitive(t *testing.T) {
	lower, ok := uiddict.Dictionary.ByKeyword("ctimagestorage")
	if !ok {
		t.Fatal(`ByKeyword("ctimagestorage") did not find entry`)
	}

	mixed, ok := uiddict.Dictionary.ByKeyword("CTImageStorage")
	if !ok {
		t.Fatal(`ByKeyword("CTImageStorage") did not find entry`)
	}

	upper, ok := uiddict.Dictionary.ByKeyword("CTIMAGESTORAGE")
	if !ok {
		t.Fatal(`ByKeyword("CTIMAGESTORAGE") did not find entry`)
	}

	if lower != mixed || mixed != upper {
		t.Fatalf("case-insensitive lookup mismatch:\nlower=%#v\nmixed=%#v\nupper=%#v", lower, mixed, upper)
	}
}

func TestDictionaryReturnsFalseForUnknownUID(t *testing.T) {
	got, ok := uiddict.Dictionary.ByUID("1.2.840.10008.999.999")
	if ok {
		t.Fatalf("ByUID unexpectedly found %#v", got)
	}
	if got != (uiddict.Entry{}) {
		t.Fatalf("ByUID = %#v, want zero Entry", got)
	}
}

func TestDictionaryRetiredEntryFlag(t *testing.T) {
	want := uiddict.Entry{
		UID:     "1.2.840.10008.1.2.2",
		Name:    "Explicit VR Big Endian (Retired)",
		Keyword: "ExplicitVRBigEndian",
		Type:    uiddict.TransferSyntax,
		Retired: true,
	}

	got, ok := uiddict.Dictionary.ByUID(want.UID)
	if !ok {
		t.Fatalf("ByUID(%q) did not find retired entry", want.UID)
	}
	if got != want {
		t.Fatalf("ByUID(%q) = %#v, want %#v", want.UID, got, want)
	}
}

func TestEntriesByTypeReturnsTransferSyntaxes(t *testing.T) {
	entries := uiddict.EntriesByType(uiddict.TransferSyntax)
	if len(entries) < 40 {
		t.Fatalf("transfer syntax entry count = %d, want at least 40", len(entries))
	}

	found := false
	for _, entry := range entries {
		if entry.UID == "1.2.840.10008.1.2.1" {
			found = true
			if entry.Name != "Explicit VR Little Endian" {
				t.Fatalf("unexpected name for Explicit VR Little Endian: %q", entry.Name)
			}
			break
		}
	}
	if !found {
		t.Fatal("EntriesByType(TransferSyntax) did not include Explicit VR Little Endian")
	}
}

func TestGeneratedEntriesFileHasGeneratedHeader(t *testing.T) {
	data, err := os.ReadFile("std_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "Code generated by cmd/dicomuidgen; DO NOT EDIT.") {
		t.Fatal("std_gen.go is missing generated-file header")
	}
	if !strings.Contains(text, "Source file: internal/standard/uids.tsv") {
		t.Fatal("std_gen.go is missing normalized source path header")
	}
	if count := strings.Count(text, "UID: "); count < 400 {
		t.Fatalf("std_gen.go has %d entries, want at least 400", count)
	}
}
