package std_test

import (
	"os"
	"strings"
	"testing"

	"github.com/ThalesMMS/dicom-go/core"
	"github.com/ThalesMMS/dicom-go/dictionary"
	"github.com/ThalesMMS/dicom-go/dictionary/std"
)

func TestDictionaryByTagCriticalEntries(t *testing.T) {
	tests := []dictionary.Entry{
		{Tag: core.NewTag(0x0002, 0x0010), VR: core.VRUI, Keyword: "TransferSyntaxUID", Name: "Transfer Syntax UID", VM: "1"},
		{Tag: core.NewTag(0x0008, 0x0060), VR: core.VRCS, Keyword: "Modality", Name: "Modality", VM: "1"},
		{Tag: core.NewTag(0x0010, 0x0010), VR: core.VRPN, Keyword: "PatientName", Name: "Patient Name", VM: "1"},
		{Tag: core.NewTag(0x7FE0, 0x0010), VR: core.VROW, Keyword: "PixelData", Name: "Pixel Data", VM: "1"},
	}

	for _, want := range tests {
		got, ok := std.Dictionary.ByTag(want.Tag)
		if !ok {
			t.Fatalf("ByTag(%v) did not find %q", want.Tag, want.Keyword)
		}
		if got != want {
			t.Fatalf("ByTag(%v) = %#v, want %#v", want.Tag, got, want)
		}
	}
}

func TestDictionaryByKeywordIsCaseInsensitive(t *testing.T) {
	lower, ok := std.Dictionary.ByKeyword("patientname")
	if !ok {
		t.Fatal(`ByKeyword("patientname") did not find entry`)
	}

	mixed, ok := std.Dictionary.ByKeyword("PatientName")
	if !ok {
		t.Fatal(`ByKeyword("PatientName") did not find entry`)
	}

	upper, ok := std.Dictionary.ByKeyword("PATIENTNAME")
	if !ok {
		t.Fatal(`ByKeyword("PATIENTNAME") did not find entry`)
	}

	if lower != mixed || mixed != upper {
		t.Fatalf("case-insensitive lookup mismatch:\nlower=%#v\nmixed=%#v\nupper=%#v", lower, mixed, upper)
	}
}

func TestDictionaryByKeywordUsesCanonicalEntry(t *testing.T) {
	got, ok := std.Dictionary.ByKeyword("pixeldata")
	if !ok {
		t.Fatal(`ByKeyword("pixeldata") did not find entry`)
	}
	want := dictionary.Entry{
		Tag:     core.NewTag(0x7FE0, 0x0010),
		VR:      core.VROW,
		Keyword: "PixelData",
		Name:    "Pixel Data",
		VM:      "1",
	}
	if got != want {
		t.Fatalf(`ByKeyword("pixeldata") = %#v, want %#v`, got, want)
	}
}

func TestDictionaryRetiredEntryFlag(t *testing.T) {
	want := dictionary.Entry{
		Tag:     core.NewTag(0x0004, 0x1504),
		VR:      core.VRUL,
		Keyword: "MRDRDirectoryRecordOffset",
		Name:    "MRDR Directory Record Offset",
		VM:      "1",
		Retired: true,
	}

	got, ok := std.Dictionary.ByTag(want.Tag)
	if !ok {
		t.Fatalf("ByTag(%v) did not find retired entry", want.Tag)
	}
	if got != want {
		t.Fatalf("ByTag(%v) = %#v, want %#v", want.Tag, got, want)
	}
}

func TestDictionaryByTagReturnsFalseForUnknownTag(t *testing.T) {
	tag := core.NewTag(0x9999, 0x0001)

	got, ok := std.Dictionary.ByTag(tag)
	if ok {
		t.Fatalf("ByTag(%v) unexpectedly found %#v", tag, got)
	}
	if got != (dictionary.Entry{}) {
		t.Fatalf("ByTag(%v) = %#v, want zero Entry", tag, got)
	}
}

func TestGeneratedEntriesFileHasGeneratedHeader(t *testing.T) {
	data, err := os.ReadFile("std_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "Code generated by cmd/dicomdictgen; DO NOT EDIT.") {
		t.Fatal("std_gen.go is missing generated-file header")
	}
	if !strings.Contains(text, "Source file: internal/standard/dicom.dic") {
		t.Fatal("std_gen.go is missing normalized source path header")
	}
	if !strings.Contains(text, "Source URL: https://raw.githubusercontent.com/DCMTK/dcmtk/master/dcmdata/data/dicom.dic") {
		t.Fatal("std_gen.go is missing source URL header")
	}
	if !strings.Contains(text, "Generated at: ") {
		t.Fatal("std_gen.go is missing generation timestamp header")
	}
	if count := strings.Count(text, "Keyword: "); count < 4000 {
		t.Fatalf("std_gen.go has %d entries, want at least 4000", count)
	}
}
